export const ACTIONS = {
  FIND_COUNTRY: "FIND_COUNTRY",
  FILTER_COUNTRY_LIST: "FILTER_COUNTRY_LIST",
  SET_COUNTRY_LIST: "SET_COUNTRY_LIST",
  ADD_TO_FAV: "ADD_TO_FAV",
  SET_LANGUAGE: "SET_LANGUAGE"
};
